/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mike' at '11/23/17 9:35 PM' with Gradle 3.0
 *
 * @author mike, @date 11/23/17 9:35 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
